### ISSUE TITLE
Rename "Supported languages" section

### ISSUE THREAD

**Issue by filips123** [OctoLinker/octolinker.now.sh#2]
Section "Supported languages" on the website should be renamed or changed. It not only contains languages but also package managers. It should probably be renamed to "Supported languages and package managers" or something like this.

**Comment by stefanbuck** [comment]
Thanks for your suggestion. I know it's not ideal, but I would like to avoid a rather lengthly title which is the reason why I went with just languages. I'm open for other suggestions

**Comment by xt0rted** [comment]
@stefanbuck how about `Supported environments`?

**Comment by stefanbuck** [comment]
Great suggestion Brain. I'm going to update the code
