### ISSUE TITLE
Display "Install from" button depending on current browser

### ISSUE THREAD

**Issue by filips123** [OctoLinker/octolinker.now.sh#3]
You should "Install from" button depending on current browser (based on user-agent). If the user is using Chrome, it should display "Install for Google Chrome", if it is using Firefox, it should display "Install for Mozilla Firefox" and if it is using Opera, it should display "Install for Opera", with link to correct addon store.

**Comment by stefanbuck** [comment]
Thanks, this was an issue with my implementation which has been fixed since quite a while and I forgot to close this issue

https://github.com/OctoLinker/octolinker.now.sh/commit/8010077fd18c89102d7fc55bd525a6996be4af62
