### ISSUE TITLE
Add .net to the list of supported languages

### ISSUE THREAD

**Issue by xt0rted** [OctoLinker/octolinker.now.sh#51]
Someone on twitter pointed out that there's no mention of .net being supported.

Some logos can be found here https://github.com/dotnet/swag/tree/master/netlogo but most of the spots on https://dotnet.microsoft.com are just plain text and there's a couple that aren't in this repo so I'm not sure what the correct logo to use would be.

**Comment by xt0rted** [comment]
The correct logo can now be found at https://github.com/dotnet/brand

**Comment by stefanbuck** [comment]
Ohh, for whatever reason I was not watching this repo. I just added the .Net logo.
